    username = "root"
    port = 3306
    database = "vehicleCD"
    csv_name = "./data/data.csv"
    xy_csv_name = "./data/xy_data.csv"
    fill_xy_csv_name = "./data/fill_xy.csv"

    start_time = "2014-08-20 09:00:00"
    stop_time = "2014-08-20 09:05:00"

    zone_length = 3000
    base_latitude = 30.646166
    base_longitude = 104.045824